
#Chinmay Keskar , Harmehar Singh
#November 29th, 2019
#Hangman - Automobile Variation
#How to build a hangman game with a car theme?

import random #importing random module 
 #Chinmay
#Defining a function called startmenu that gives allows the user to help, start or quit
def startmenu():
    helpmenu = input('Welcome to Hangman - Automobile Edition! Press s to start, q to quit, or h for help: ')
    return helpmenu
    # Declaring global variables & lists  
lives= 5
right = 0
guesses= []
######################################################################
#Chinmay
#defining a function called rulesmenu that prints the rules of the game
def rulesmenu():
    print(' ')
    print('Welcome to Automobile Hangman')
    print('The Rules are that of Classic Hangman.')
    print('You have to keep guessing at a random car-related word generated by the program.')
    print('You win by getting all of the words correct, but lose if you get five incorrect.')
    print('A single hint is available each game if needed.')
    print('Good Luck!')
    print(' ')
#Chinmay
#defining a function called endmenu that prints user a farewell message
def endmenu():
  print('Thank you for playing Automobile Hangman! Goodbye Now')

##########################################################################

#Chinmay
#defining a function called get_word that gets passed wordlist
#assigns word a random element from wordlist
def get_word(wordlist): 
  word = random.choice(wordlist)  
  return word

#################################################################
def ask_hint():
  user_input= input('Hint: y for yes or n for no: ')
  return user_input
#################################################################
#defining a function called get_hints that gets passed word and wordlist
#Chinmay
def get_hints(word): 
  if word == 'whel':
    print('The ____ on the bus...')
  elif word == 'axle' :
    print('This part bears the weight of the car and its contents.')
  elif word == 'bumper':
    print('This Prevents damage in the case of a collision.')
  elif word == 'piston':
    print('This produces the energy of the engine.')
  elif word=='engin':
    print('This converts chemical energy into kinetic energy.')
  elif word == 'acelrto':
    print('This is also known as the gas pedal.')
  elif word == 'exhaust':
    print('This part contributes to global warming.')
  elif word == 'transmission':
    print('This makes sure that the right amount of power go into the tires.')
  elif word == 'ignton':
    print('This ignites the fuel in the cylinder of a car and you use it start a car.')
  elif word == 'spedomtr':
    print('This displays the cars rate of displacement.')
  elif word == 'raditor':
    print('These exchange the heat in a cars combustion chamber to cool it down.')
  else:
    print("you've chosen to go without hints - good luck.")
###########################################################################
#Chinmay
#calling a function called wordslicer that is passed the word.
#it slices the word and returns it as sliceword
def wordslicer(word):
  sliceword = [word[0:1], word[1:2], word[2:3], word[3:4], word[4:5],word[5:6], word[6:7], word[7:8], word[8:9], word[9:10], word[10:11],word[11:12]]   
  return sliceword
###########################################################################
#chinmay - exception handling by Harmehar
#defining a function called get_guess
#it tries guess and prints an error message if a value error occurs
def get_guess():   
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    guess = input("Please enter your guess:")
    if guess == '' or guess == ' ':
        print("Please enter valid input.")        
    elif guess not in alphabet:
        print("You must enter an alphabetic character.")
    else:
      return guess
######################################################################
def ASCII_hangman() :
  hangman_pics = ['''
   +---+

   |   |

       |

       |

       |

       |
 =========''', '''
   +---+
   |   |

   O   |

       |

       |

       |
 =========''', '''
   +---+

   |   |

   O   |

  /|  |

       |

       |
 =========''', '''
   +---+

   |   |

   O   |

  /|\  |

       |

       |
 =========''', '''
   +---+

   |   |

   O   |

  /|\  |

  /    |

       |
 =========''', '''
   +---+

   |   |

   O   |

  /|\  |

  / \ |

       |
 ========='''] 
  return hangman_pics
######################################################################
# This funtion produces the result for the user getting a right guess and if they win the game.
#Harmehar
def correct_guess(wordlength, hangman_pics, right, options):
  if right!= wordlength:        
    print('correct.')
    print(hangman_pics[0])    
  elif right == wordlength:
    print('You got it right!' + ' ' + 'the word was:' + word)
    options= False
    return options  
######################################################################
#This function is for the user providing a wrong guess and losing the game 
#Harmehar
def wrong_guess(lives, hangman_pics, options):   
  if lives==4:
    print('Wrong.')
    print(hangman_pics[1])
  elif lives== 3:
    print('Wrong again. Your buddy is losing time.')
    print(hangman_pics[2])       
  elif lives== 2:
    print('Nope. Keep trying, you still have time.')
    print(hangman_pics[3]) 
  elif lives== 1:
    print('You have one last chance.')
    print(hangman_pics[4])       
  elif lives== 0:
    print('Your buddy is gone. You lost.')
    print(hangman_pics[5])
    options= False    
  return options  
#################################################################
#################################################################
#below part done by Harmehar
options= True
while options:
  hangman= ASCII_hangman() 
  wordlist = ['whel','axle','bumper','piston','engin','acelrto','exhaust','transmio','ignton','spedomtr','raditor']
  helpmenu = startmenu()
  if helpmenu == 'h':
    rulesmenu()   
  elif helpmenu == 's':
    word= get_word(wordlist)
    user_input= ask_hint()
    if user_input== 'y':  
      hint = get_hints(word)    
    elif user_input== 'n':
      print('Please carry on')
    else:
      print('Invalid input')
      user_input= ask_hint()
      if user_input== 'y':  
        hint = get_hints(word)    
      elif user_input== 'n':
        print('Please carry on')      
    letters= wordslicer(word)
    
    create = True    
    while create :
      guess = get_guess()
      
      if guess in guesses:
        print(' Try again ')
        guess=get_guess()
      else:
        wordlength= len(word)
        guesses.append(guess) 
        choice = guess in letters           
        if choice== True:        
          options = correct_guess(wordlength, hangman, right, options)
          right+=1
        elif choice == False:
          lives -= 1
          options= wrong_guess(lives, hangman, options)         
  elif helpmenu == 'q':
    options = False
    endmenu()
    
  else:
    print ('Invalid input')

